#!/usr/bin/env python3
"""Generate the citation inventory from the bundled reference data.

CITATIONS.md is generated rather than hand-written so it cannot drift from the
JSON it describes. A test asserts the committed file matches what this produces.

Usage:
    python3 backend/scripts/generate_citations.py           # write the file
    python3 backend/scripts/generate_citations.py --check    # exit 1 if stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from suas.reference_data import (  # noqa: E402
    AIRCRAFT_FILE,
    DATA_DIR,
    PAYLOAD_FILE,
    ReferenceEntry,
    load_entries,
)
from suas.schemas.provenance import OPERATIONAL_GRADE  # noqa: E402

OUTPUT: Path = DATA_DIR / "CITATIONS.md"

HEADER: str = """# Citation inventory

**Generated by `backend/scripts/generate_citations.py`. Do not edit by hand.**

Every numeric field in the bundled reference data, and where it came from. This
file exists to make the gap visible: a figure with no `source_url` is one nobody
has traced to a primary document, and the operational gate treats it that way.

| Source | Meaning | Good enough to fly on |
| --- | --- | --- |
| `datasheet` | Read from the manufacturer's own published document | yes |
| `flight_log` | Measured from recorded flight telemetry | yes |
| `secondary` | Published figure from a specification summary, not the primary document | no |
| `derived` | Computed from other fields by a formula in the notes | no |
| `estimate` | An engineering estimate | no |
| `unknown` | Provenance not recorded. Nobody vouched for this number | no |
"""


def _summary(entries: list[ReferenceEntry]) -> dict[str, int]:
    """Return a count of fields by source across every entry."""
    counts: dict[str, int] = {}
    for entry in entries:
        for record in entry.provenance.values():
            counts[record.source.value] = counts.get(record.source.value, 0) + 1
    return counts


def _table(entry: ReferenceEntry) -> list[str]:
    """Return the markdown rows describing one entry."""
    lines: list[str] = [
        f"### {entry.name} (`{entry.id}`)",
        "",
        "| Field | Value | Unit | Source | URL | Confidence | Notes |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for field in sorted(entry.provenance):
        record = entry.provenance[field]
        url: str = record.source_url or "-"
        notes: str = record.notes.replace("|", "\\|") or "-"
        lines.append(
            f"| `{field}` | {record.value} | {record.unit} | `{record.source.value}` | "
            f"{url} | {record.confidence.value} | {notes} |"
        )
    lines.append("")
    return lines


def render() -> str:
    """Return the full citation inventory as markdown."""
    aircraft: list[ReferenceEntry] = load_entries(AIRCRAFT_FILE)
    payloads: list[ReferenceEntry] = load_entries(PAYLOAD_FILE)
    counts: dict[str, int] = _summary(aircraft + payloads)
    total: int = sum(counts.values())
    flyable: int = sum(count for source, count in counts.items() if source in OPERATIONAL_GRADE)

    lines: list[str] = [HEADER, "## Summary", ""]
    lines.append(
        f"{total} numeric fields across {len(aircraft)} airframes and {len(payloads)} "
        f"payloads. **{flyable}** are good enough to fly on."
    )
    lines.append("")
    lines.append("| Source | Fields |")
    lines.append("| --- | --- |")
    for source in sorted(counts):
        lines.append(f"| `{source}` | {counts[source]} |")
    lines.append("")
    lines.append("## Airframes")
    lines.append("")
    for entry in aircraft:
        lines.extend(_table(entry))
    lines.append("## Payloads")
    lines.append("")
    for entry in payloads:
        lines.extend(_table(entry))
    return "\n".join(lines).rstrip("\n") + "\n"


def main() -> int:
    """Write or verify the citation inventory."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 when the file is stale")
    parsed = parser.parse_args()

    rendered: str = render()
    if not parsed.check:
        OUTPUT.write_text(rendered, encoding="utf-8")
        print(f"wrote {OUTPUT}")
        return 0

    current: str = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
    if current == rendered:
        print("CITATIONS.md is current.")
        return 0
    print(
        "error: CITATIONS.md is stale. Run:\n  python3 backend/scripts/generate_citations.py",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
