#!/usr/bin/env python3
"""Create the planning backlog as GitHub issues from docs/backlog/*.md.

Each backlog file carries YAML-ish front matter (title, labels, blocked_by)
followed by the issue body. Issues are created in filename order, then a second
pass appends real "Blocked by" references once numbers are known.

Requires the `gh` CLI, authenticated with issue write access:

    gh auth status
    python3 scripts/open_backlog_issues.py --dry-run
    python3 scripts/open_backlog_issues.py
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

BACKLOG_DIR: Path = Path(__file__).resolve().parent.parent / "docs" / "backlog"
FOOTER: str = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"
DELIMITER: str = "---"


@dataclass(frozen=True)
class BacklogItem:
    """One backlog file, parsed."""

    index: int
    title: str
    labels: tuple[str, ...]
    blocked_by: tuple[int, ...]
    body: str


def _parse_list(raw: str) -> list[str]:
    """Parse a bracketed inline list such as ``[phase-1, seal]``."""
    stripped: str = raw.strip().strip("[]").strip()
    if not stripped:
        return []
    return [part.strip().strip('"') for part in stripped.split(",") if part.strip()]


def parse_item(path: Path) -> BacklogItem:
    """Read one backlog file into a BacklogItem, or raise ValueError."""
    text: str = path.read_text(encoding="utf-8")
    lines: list[str] = text.split("\n")
    if not lines or lines[0].strip() != DELIMITER:
        raise ValueError(f"{path.name}: missing opening '{DELIMITER}'")
    try:
        end: int = lines.index(DELIMITER, 1)
    except ValueError as exc:
        raise ValueError(f"{path.name}: missing closing '{DELIMITER}'") from exc

    title: str = ""
    labels: list[str] = []
    blocked_by: list[int] = []
    for line in lines[1:end]:
        key, _, value = line.partition(":")
        field: str = key.strip()
        if field == "title":
            title = value.strip().strip('"')
        elif field == "labels":
            labels = _parse_list(value)
        elif field == "blocked_by":
            blocked_by = [int(n) for n in _parse_list(value)]

    if not title:
        raise ValueError(f"{path.name}: front matter has no title")

    return BacklogItem(
        index=int(path.name.split("-", 1)[0]),
        title=title,
        labels=tuple(labels),
        blocked_by=tuple(blocked_by),
        body="\n".join(lines[end + 1 :]).strip(),
    )


def load_backlog(directory: Path) -> list[BacklogItem]:
    """Return every backlog item in filename order."""
    paths: list[Path] = sorted(p for p in directory.glob("*.md") if p.name != "README.md")
    if not paths:
        raise ValueError(f"no backlog files found in {directory}")
    return [parse_item(path) for path in paths]


def _run_gh(args: list[str]) -> str:
    """Run a gh command, returning stdout. Raises RuntimeError on failure."""
    try:
        result = subprocess.run(
            ["gh", *args], capture_output=True, text=True, check=True, timeout=60
        )
    except FileNotFoundError as exc:
        raise RuntimeError("gh CLI not found on PATH") from exc
    except subprocess.TimeoutExpired as exc:
        raise RuntimeError(f"gh timed out: {' '.join(args)}") from exc
    except subprocess.CalledProcessError as exc:
        raise RuntimeError(f"gh failed: {exc.stderr.strip()}") from exc
    return result.stdout.strip()


LABEL_COLORS: dict[str, str] = {
    "phase-1": "0e8a16",
    "phase-2": "1d76db",
    "phase-3": "5319e7",
    "seal": "b60205",
    "security": "d93f0b",
    "data": "fbca04",
    "infra": "006b75",
    "eval": "0052cc",
    "ci": "5a5a5a",
}


def ensure_labels(items: list[BacklogItem], repo: str) -> None:
    """Create any label the backlog uses. Existing labels are left alone."""
    wanted: set[str] = {label for item in items for label in item.labels}
    for label in sorted(wanted):
        color: str = LABEL_COLORS.get(label, "ededed")
        try:
            _run_gh(["label", "create", label, "--repo", repo, "--color", color])
        except RuntimeError as exc:
            if "already exists" not in str(exc):
                print(f"warning: label '{label}': {exc}", file=sys.stderr)


def create_issue(item: BacklogItem, repo: str) -> int:
    """Create one issue and return its number."""
    args: list[str] = [
        "issue", "create", "--repo", repo,
        "--title", item.title,
        "--body", item.body + FOOTER,
    ]
    for label in item.labels:
        args.extend(["--label", label])
    url: str = _run_gh(args)
    return int(url.rstrip("/").rsplit("/", 1)[-1])


def append_blockers(number: int, item: BacklogItem, created: dict[int, int], repo: str) -> None:
    """Append a 'Blocked by' line once every issue number is known."""
    refs: list[str] = [f"#{created[dep]}" for dep in item.blocked_by if dep in created]
    if not refs:
        return
    body: str = _run_gh(["issue", "view", str(number), "--repo", repo, "--json", "body"])
    current: str = json.loads(body)["body"]
    updated: str = current.replace(FOOTER, f"\n\nBlocked by {', '.join(refs)}.{FOOTER}")
    _run_gh(["issue", "edit", str(number), "--repo", repo, "--body", updated])


def main() -> int:
    """Parse arguments, create issues, wire up blockers."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", default="MatthewK84/LangGraphUAS")
    parser.add_argument("--dry-run", action="store_true", help="print titles and exit")
    parsed = parser.parse_args()

    try:
        items: list[BacklogItem] = load_backlog(BACKLOG_DIR)
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if parsed.dry_run:
        for item in items:
            blockers: str = f" (blocked by {list(item.blocked_by)})" if item.blocked_by else ""
            print(f"{item.index:02d} [{', '.join(item.labels)}] {item.title}{blockers}")
        return 0

    ensure_labels(items, parsed.repo)

    created: dict[int, int] = {}
    for item in items:
        try:
            number: int = create_issue(item, parsed.repo)
        except RuntimeError as exc:
            print(f"error creating '{item.title}': {exc}", file=sys.stderr)
            print(f"created so far: {created}", file=sys.stderr)
            return 1
        created[item.index] = number
        print(f"#{number} {item.title}")

    for item in items:
        try:
            append_blockers(created[item.index], item, created, parsed.repo)
        except RuntimeError as exc:
            print(f"warning: blockers for #{created[item.index]}: {exc}", file=sys.stderr)

    print(f"\n{len(created)} issues created.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
